import { getAppOrigin } from "./app-url";

export const env = {
  NODE_ENV: process.env.NODE_ENV ?? "development",
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL ? getAppOrigin(process.env.NEXT_PUBLIC_APP_URL) : undefined,
  AUTH_SHARED_KEY: process.env.AUTH_SHARED_KEY,
  CRON_SECRET: process.env.CRON_SECRET,
  AUTH_COOKIE_SECRET: process.env.AUTH_COOKIE_SECRET,
  AUDIT_SIGNING_SECRET: process.env.AUDIT_SIGNING_SECRET,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  RESEND_LOGIN_FROM: process.env.RESEND_LOGIN_FROM ?? "logins@kevinbytes.com",

  // Stripe
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  STRIPE_PRO_PRICE_ID: process.env.STRIPE_PRO_PRICE_ID,
  STRIPE_SMB_PRICE_ID: process.env.STRIPE_SMB_PRICE_ID,
  STRIPE_ENTERPRISE_PRICE_ID: process.env.STRIPE_ENTERPRISE_PRICE_ID,

  DATABASE_URL: process.env.NEON_DATABASE_URL || process.env.DATABASE_URL,
  UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL ?? process.env.KV_REST_API_URL,
  UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN ?? process.env.KV_REST_API_TOKEN,
  EXCHANGE_RATE_API_URL: process.env.EXCHANGE_RATE_API_URL ?? "https://api.exchangerate.host/latest",
  ALLOW_SELF_REGISTRATION: process.env.ALLOW_SELF_REGISTRATION === "true",
  ALLOW_BOOTSTRAP_OWNER: process.env.ALLOW_BOOTSTRAP_OWNER !== "false",

  // Workspace integrations
  GOOGLE_CALENDAR_CLIENT_ID: process.env.GOOGLE_CALENDAR_CLIENT_ID,
  GOOGLE_CALENDAR_CLIENT_SECRET: process.env.GOOGLE_CALENDAR_CLIENT_SECRET,
  GOOGLE_CALENDAR_REDIRECT_URI: process.env.GOOGLE_CALENDAR_REDIRECT_URI,
  SLACK_CLIENT_ID: process.env.SLACK_CLIENT_ID,
  SLACK_CLIENT_SECRET: process.env.SLACK_CLIENT_SECRET,
  SLACK_REDIRECT_URI: process.env.SLACK_REDIRECT_URI,
  QUICKBOOKS_CLIENT_ID: process.env.QUICKBOOKS_CLIENT_ID,
  QUICKBOOKS_CLIENT_SECRET: process.env.QUICKBOOKS_CLIENT_SECRET,
  QUICKBOOKS_REDIRECT_URI: process.env.QUICKBOOKS_REDIRECT_URI,
  QUICKBOOKS_ENVIRONMENT: process.env.QUICKBOOKS_ENVIRONMENT ?? "sandbox",
};
