import type { InvoiceProofPack } from "@/lib/invoice-proof-pack";

function escapeHtml(value: unknown) {
  return String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
}

export function renderInvoicePrint(proof: InvoiceProofPack, digest: string) {
  const money = (amount: number) => `$${amount.toFixed(2)}`;
  const invoice = proof.invoice;
  const rows = proof.entries.map((entry) => `<tr><td>${escapeHtml(entry.startedAt?.slice(0, 10))}</td><td><strong>${escapeHtml(entry.taskId)}</strong><br>${escapeHtml(entry.description)}<br><small>${escapeHtml(entry.projectName)} · ${escapeHtml(entry.source)}</small></td><td>${(entry.durationSeconds / 3600).toFixed(2)}</td><td>${entry.hourlyRate === null ? "—" : money(entry.hourlyRate)}</td><td>${money(entry.amount)}</td></tr>`).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(invoice.number)} — SOWLedger</title><style>body{font:15px/1.5 system-ui,sans-serif;color:#172033;margin:0;background:#f6f3ee}main{max-width:850px;margin:32px auto;padding:40px;background:white}header{display:flex;justify-content:space-between;gap:24px}h1{margin:0;font-size:28px}p{margin:6px 0}table{width:100%;border-collapse:collapse;margin:32px 0}th,td{text-align:left;padding:12px 8px;border-bottom:1px solid #ddd;vertical-align:top}th:nth-last-child(-n+3),td:nth-last-child(-n+3){text-align:right;white-space:nowrap}.total{text-align:right;font-size:22px}.digest{font:11px/1.6 monospace;overflow-wrap:anywhere}.actions{margin-bottom:24px}button{padding:10px 16px;cursor:pointer}.note{color:#526070;font-size:13px}@media(max-width:600px){main{padding:20px;margin:0}header{display:block}.table-wrap{overflow:auto}}@media print{body{background:white}main{margin:0;padding:0;max-width:none}.actions{display:none}thead{display:table-header-group}tr{break-inside:avoid}}</style></head><body><main><div class="actions"><button onclick="window.print()">Print or save PDF</button><p class="note">Only this invoice is printed.</p></div><header><div><h1>Invoice ${escapeHtml(invoice.number)}</h1><p>${escapeHtml(invoice.projectName)}</p></div><div><p>Created: ${escapeHtml(invoice.createdAt?.slice(0, 10))}</p><p>Due: ${escapeHtml(invoice.dueDate?.slice(0, 10) ?? "Not set")}</p><p>Status: ${escapeHtml(invoice.status)}</p></div></header><div class="table-wrap"><table><thead><tr><th>Date</th><th>Work</th><th>Hours</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${rows}</tbody></table></div><p class="total">Total: ${money(invoice.amount)}</p><p class="note">${proof.entries.length} time entries · ${proof.totals.actualHours.toFixed(2)} hours</p><hr><p class="note">Invoice status is recorded by the workspace. SOWLedger does not send this invoice or process payment.</p><p class="digest">Reviewed details SHA-256: ${escapeHtml(digest)}</p></main></body></html>`;
}
